-- MySQL Script generated by MySQL Workbench
-- qua 11 jun 2025 08:41:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzaria` ;
USE `pizzaria` ;

-- -----------------------------------------------------
-- Table `pizzaria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_ani` DATE NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(255) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(80) NOT NULL,
  `email` VARCHAR(90) NOT NULL,
  `senha` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`delivery` (
  `iddelivery` INT NOT NULL AUTO_INCREMENT,
  `endereco_entrega` VARCHAR(45) NOT NULL,
  `tempo_entrega` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddelivery`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`feedback` (
  `idfeedback` INT NOT NULL AUTO_INCREMENT,
  `assunto` VARCHAR(45) NOT NULL,
  `comentario` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`idfeedback`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`bebidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`bebidas` (
  `idbebidas` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `quantidade` INT NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idbebidas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pizza` (
  `idpizza` INT NOT NULL AUTO_INCREMENT,
  `variedade` VARCHAR(45) NOT NULL,
  `tamanho` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `quantidade` INT NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idpizza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pagamento` (
  `idpagamento` INT NOT NULL AUTO_INCREMENT,
  `metodo_pagamento` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `status_pagamento` VARCHAR(45) NOT NULL,
  `data_pagamento` DATE NOT NULL,
  PRIMARY KEY (`idpagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `delivery` INT NOT NULL,
  `cliente` INT NOT NULL,
  `idfeedback` INT NULL,
  `idpagamento1` INT NOT NULL,
  PRIMARY KEY (`idpedido`, `idfeedback`, `idpagamento1`, `cliente`, `delivery`),
  INDEX `fk_pedido_delivery1_idx` (`delivery` ASC) VISIBLE,
  INDEX `fk_pedido_cliente1_idx` (`cliente` ASC) VISIBLE,
  INDEX `fk_pedido_feedback1_idx` (`idfeedback` ASC) VISIBLE,
  INDEX `fk_pedido_pagamento1_idx` (`idpagamento1` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_delivery1`
    FOREIGN KEY (`delivery`)
    REFERENCES `pizzaria`.`delivery` (`iddelivery`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `pizzaria`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_feedback1`
    FOREIGN KEY (`idfeedback`)
    REFERENCES `pizzaria`.`feedback` (`idfeedback`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_pagamento1`
    FOREIGN KEY (`idpagamento1`)
    REFERENCES `pizzaria`.`pagamento` (`idpagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`promocao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`promocao` (
  `idpromocao` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `preco` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(455) NOT NULL,
  PRIMARY KEY (`idpromocao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`pedido_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pedido_pizza` (
  `idpedido_pedido` INT NOT NULL,
  `idfeedback_pedido` INT NOT NULL,
  `idpagamento_pagamento_pedido` INT NOT NULL,
  `idpizza_pizza` INT NOT NULL,
  PRIMARY KEY (`idpedido_pedido`, `idfeedback_pedido`, `idpagamento_pagamento_pedido`, `idpizza_pizza`),
  INDEX `fk_pedido_pizza_pizza1_idx` (`idpizza_pizza` ASC) VISIBLE,
  INDEX `fk_pedido_pizza_pedido1_idx` (`idpedido_pedido` ASC, `idfeedback_pedido` ASC, `idpagamento_pagamento_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_pizza_pedido1`
    FOREIGN KEY (`idpedido_pedido` , `idfeedback_pedido` , `idpagamento_pagamento_pedido`)
    REFERENCES `pizzaria`.`pedido` (`idpedido` , `idfeedback` , `idpagamento1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_pizza_pizza1`
    FOREIGN KEY (`idpizza_pizza`)
    REFERENCES `pizzaria`.`pizza` (`idpizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`pedido_promocao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pedido_promocao` (
  `idpedido_pedido` INT NOT NULL,
  `idfeedback_pedido` INT NOT NULL,
  `idpagamento_pagamento_pedido` INT NOT NULL,
  `idpromocao_promocao` INT NOT NULL,
  PRIMARY KEY (`idpedido_pedido`, `idfeedback_pedido`, `idpagamento_pagamento_pedido`, `idpromocao_promocao`),
  INDEX `fk_pedido_promocao_promocao1_idx` (`idpromocao_promocao` ASC) VISIBLE,
  INDEX `fk_pedido_promocao_pedido1_idx` (`idpedido_pedido` ASC, `idfeedback_pedido` ASC, `idpagamento_pagamento_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_promocao_pedido1`
    FOREIGN KEY (`idpedido_pedido` , `idfeedback_pedido` , `idpagamento_pagamento_pedido`)
    REFERENCES `pizzaria`.`pedido` (`idpedido` , `idfeedback` , `idpagamento1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_promocao_promocao1`
    FOREIGN KEY (`idpromocao_promocao`)
    REFERENCES `pizzaria`.`promocao` (`idpromocao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`pedido_bebidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pedido_bebidas` (
  `idpedido_pedido` INT NOT NULL,
  `idfeedback_pedido` INT NOT NULL,
  `idpagamento_pagamento_pedido` INT NOT NULL,
  `idbebidas_bebidas` INT NOT NULL,
  PRIMARY KEY (`idpedido_pedido`, `idfeedback_pedido`, `idpagamento_pagamento_pedido`, `idbebidas_bebidas`),
  INDEX `fk_pedido_bebidas_bebidas1_idx` (`idbebidas_bebidas` ASC) VISIBLE,
  INDEX `fk_pedido_bebidas_pedido1_idx` (`idpedido_pedido` ASC, `idfeedback_pedido` ASC, `idpagamento_pagamento_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_bebidas_pedido1`
    FOREIGN KEY (`idpedido_pedido` , `idfeedback_pedido` , `idpagamento_pagamento_pedido`)
    REFERENCES `pizzaria`.`pedido` (`idpedido` , `idfeedback` , `idpagamento1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_bebidas_bebidas1`
    FOREIGN KEY (`idbebidas_bebidas`)
    REFERENCES `pizzaria`.`bebidas` (`idbebidas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
