-- MySQL Script generated by MySQL Workbench
-- Fri Jun 27 16:12:16 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzaria` ;
USE `pizzaria` ;

-- -----------------------------------------------------
-- Table `pizzaria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_ani` DATE NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(255) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(80) NOT NULL,
  `email` VARCHAR(90) NOT NULL,
  `senha` VARCHAR(2000) NOT NULL,
  `tipo` ENUM('cliente', 'adm') NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`delivery` (
  `iddelivery` INT NOT NULL AUTO_INCREMENT,
  `endereco_entrega` VARCHAR(45) NOT NULL,
  `tempo_entrega` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddelivery`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`feedback` (
  `idfeedback` INT NOT NULL AUTO_INCREMENT,
  `assunto` VARCHAR(45) NOT NULL,
  `comentario` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`idfeedback`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pagamento` (
  `idpagamento` INT NOT NULL AUTO_INCREMENT,
  `metodo_pagamento` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `status_pagamento` VARCHAR(45) NOT NULL,
  `data_pagamento` DATE NOT NULL,
  PRIMARY KEY (`idpagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `delivery` INT NOT NULL,
  `cliente` INT NOT NULL,
  `idfeedback` INT NULL,
  `idpagamento1` INT NOT NULL,
  `valortotal` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_delivery1_idx` (`delivery` ASC) VISIBLE,
  INDEX `fk_pedido_cliente1_idx` (`cliente` ASC) VISIBLE,
  INDEX `fk_pedido_feedback1_idx` (`idfeedback` ASC) VISIBLE,
  INDEX `fk_pedido_pagamento1_idx` (`idpagamento1` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_delivery1`
    FOREIGN KEY (`delivery`)
    REFERENCES `pizzaria`.`delivery` (`iddelivery`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `pizzaria`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_feedback1`
    FOREIGN KEY (`idfeedback`)
    REFERENCES `pizzaria`.`feedback` (`idfeedback`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_pagamento1`
    FOREIGN KEY (`idpagamento1`)
    REFERENCES `pizzaria`.`pagamento` (`idpagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `tipo` ENUM('pizza', 'bebida', 'promocao') NOT NULL,
  `tamanho` VARCHAR(45) NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`pedido_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pedido_produto` (
  `idpedido` INT NOT NULL,
  `idproduto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`idpedido`, `idproduto`),
  INDEX `fk_pedido_produto_produto1_idx` (`idproduto` ASC) VISIBLE,
  INDEX `fk_pedido_produto_pedido1_idx` (`idpedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_produto_pedido1`
    FOREIGN KEY (`idpedido`)
    REFERENCES `pizzaria`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_produto_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `pizzaria`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
